//! Accuracy checks against fixtures generated by the *reference* Python
//! implementations (`tiktoken` and HuggingFace `tokenizers`).
//!
//! The OpenAI vocabularies are compiled into the binary, so those assertions
//! always run. HuggingFace vocabularies are downloaded on demand, so those
//! cases skip with a printed note when the file is not installed rather than
//! failing a fresh clone.

use chtting_relay::config::{Config, ImageDefaults};
use chtting_relay::logging::{Level, Logger};
use chtting_relay::tokenizer::chat::count_chat_request;
use chtting_relay::tokenizer::registry::{builtin_encoder, estimate, Registry};
use chtting_relay::tokenizer::TokenCounter;
use serde_json::Value;
use std::path::PathBuf;
use std::sync::Arc;

fn fixtures() -> Value {
    let raw = include_str!("fixtures/expected-counts.json");
    serde_json::from_str(raw).expect("fixture is valid JSON")
}

fn cases(fx: &Value) -> Vec<String> {
    fx["cases"]
        .as_array()
        .expect("fixture has cases")
        .iter()
        .map(|v| v.as_str().unwrap_or_default().to_string())
        .collect()
}

#[test]
fn builtin_vocabularies_match_python_tiktoken_exactly() {
    let fx = fixtures();
    let cases = cases(&fx);

    for name in ["cl100k_base", "o200k_base"] {
        let Some(expected) = fx["counts"].get(name).and_then(|v| v.as_array()) else {
            panic!("fixture is missing counts for {name}");
        };
        let encoder = builtin_encoder(name).expect("built in");

        for (i, case) in cases.iter().enumerate() {
            let want = expected[i].as_u64().expect("count is a number") as usize;
            let got = encoder.count(case);
            assert_eq!(
                got, want,
                "{name} case {i} ({case:?}): counted {got}, python counted {want}"
            );
        }
    }
}

#[test]
fn builtin_vocabularies_produce_the_same_token_ids_not_just_the_same_totals() {
    let fx = fixtures();
    let cases = cases(&fx);
    let Some(ids) = fx.get("ids") else {
        eprintln!("fixture carries no id lists; skipping");
        return;
    };

    for name in ["cl100k_base", "o200k_base"] {
        let Some(expected) = ids.get(name).and_then(|v| v.as_array()) else {
            continue;
        };
        let encoder = builtin_encoder(name).expect("built in");
        for (i, want) in expected.iter().enumerate() {
            let Some(want) = want.as_array() else {
                continue;
            };
            let want: Vec<u32> = want
                .iter()
                .filter_map(|v| v.as_u64())
                .map(|n| n as u32)
                .collect();
            // `pieces` re-splits the text the way the model sees it; joining
            // them back must reproduce the input exactly.
            let pieces = encoder.pieces(&cases[i]);
            let joined: String = pieces.iter().map(|p| p.text.as_str()).collect();
            assert_eq!(
                joined, cases[i],
                "{name} case {i}: pieces do not reconstruct the input"
            );
            assert_eq!(
                encoder.count(&cases[i]),
                want.len(),
                "{name} case {i}: piece count differs from python's id count"
            );
        }
    }
}

/// HuggingFace vocabularies, when the user has installed them.
#[tokio::test]
async fn installed_huggingface_vocabularies_match_the_reference() {
    let fx = fixtures();
    let cases = cases(&fx);
    let dir = tokenizer_dir();
    let registry = Registry::new(dir.clone(), Logger::console(Level::Silent));

    let mut checked = 0;
    for (name, expected) in fx["counts"].as_object().expect("counts is an object") {
        if name.contains("100k") || name.contains("200k") {
            continue; // covered by the built-in test above
        }
        let encoder = registry.get(name).await;
        if !encoder.exact() {
            eprintln!(
                "skipping {name}: no vocabulary installed in {}",
                dir.display()
            );
            continue;
        }
        let expected = expected.as_array().expect("counts are a list");
        for (i, case) in cases.iter().enumerate() {
            let want = expected[i].as_u64().expect("count is a number") as usize;
            assert_eq!(
                encoder.count(case),
                want,
                "{name} case {i} ({case:?}) differs from the reference implementation"
            );
        }
        checked += 1;
    }
    eprintln!("checked {checked} installed HuggingFace vocabularies");
}

fn tokenizer_dir() -> PathBuf {
    std::env::var("CHTTING_TOKENIZER_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/tokenizers"))
}

#[test]
fn the_estimator_is_marked_inexact_so_it_is_never_mistaken_for_a_real_count() {
    let n = estimate("halo dunia, ini teks percobaan");
    assert!(n > 0);
    // It should be in the right ballpark for latin text, not wildly off.
    let real = builtin_encoder("o200k_base")
        .unwrap()
        .count("halo dunia, ini teks percobaan");
    let ratio = n as f64 / real as f64;
    assert!(
        (0.5..2.0).contains(&ratio),
        "estimator is {ratio:.2}x the real count, too far off to be useful"
    );
}

#[tokio::test]
async fn a_missing_vocabulary_degrades_to_the_estimator_rather_than_failing() {
    let registry = Registry::new(
        PathBuf::from("/nonexistent-tokenizer-dir"),
        Logger::console(Level::Silent),
    );
    let encoder = registry.get("definitely-not-installed").await;
    assert!(
        !encoder.exact(),
        "a missing vocabulary must not claim to be exact"
    );
    assert!(
        encoder.count("some text") > 0,
        "it must still produce a number"
    );
}

#[tokio::test]
async fn counting_a_chat_request_charges_template_overhead_on_top_of_the_text() {
    let registry = Arc::new(Registry::new(
        tokenizer_dir(),
        Logger::console(Level::Silent),
    ));
    let counter = TokenCounter::new(registry);
    let cfg = Config::default();

    let body = serde_json::json!({
        "messages": [
            {"role": "system", "content": "Kamu adalah penulis kreatif."},
            {"role": "user", "content": "Tulis satu paragraf tentang Termux."},
        ]
    });

    let resolved = counter.resolve(&cfg, "gpt-4o-mini", "", "");
    assert_eq!(resolved.tokenizer, "o200k_base");

    let counted = counter
        .count_request(&body, &resolved, &ImageDefaults::default())
        .await;
    assert!(counted.exact, "a built-in vocabulary is always exact");
    assert!(counted.breakdown.system > 0);
    assert!(counted.breakdown.user > 0);
    assert!(
        counted.breakdown.overhead > 0,
        "chat template tokens are billed too"
    );
    assert_eq!(counted.total, counted.breakdown.total());
}

#[test]
fn a_long_cjk_run_stays_fast_enough_for_a_phone() {
    // The pathological input for a BPE merge loop: one unbroken run with no
    // whitespace for the pre-tokenizer to split on. This guards against a
    // quadratic blowup, so the budget only has to be the right order of
    // magnitude — and an unoptimised test build is far slower than the release
    // binary a phone actually runs, so the budget follows the profile.
    let text = "这是一个没有空格的很长的中文句子".repeat(500);
    let encoder = builtin_encoder("o200k_base").unwrap();

    let started = std::time::Instant::now();
    let n = encoder.count(&text);
    let elapsed = started.elapsed();

    assert!(n > 1000);
    let budget_ms = if cfg!(debug_assertions) {
        30_000
    } else {
        3_000
    };
    assert!(
        elapsed.as_millis() < budget_ms,
        "counting {} characters took {elapsed:?}, over the {budget_ms}ms budget",
        text.chars().count()
    );
}

#[test]
fn the_chat_profiles_differ_in_the_way_their_templates_do() {
    let encoder = builtin_encoder("cl100k_base").unwrap();
    let body = serde_json::json!({
        "messages": [{"role": "user", "content": "hi"}]
    });
    let images = ImageDefaults::default();
    let raw = count_chat_request(&body, &encoder, "raw", &images).total;
    let openai = count_chat_request(&body, &encoder, "openai", &images).total;
    let llama3 = count_chat_request(&body, &encoder, "llama3", &images).total;

    assert!(raw < openai, "raw must not add template tokens");
    assert!(
        openai < llama3,
        "llama3 has the heaviest per-message header"
    );
}
